### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by jayvdb** [jazzband/website#328]
Clicking login at https://jazzband.co/ goes to https://github.com/login/oauth/authorize?client_id=692473717aaa7a89a38c&scope=read%3Aorg%2Cuser%3Aemail which is a 500 error

**Comment by jezdez** [comment]
Odd, something about the access token missing when returning from GitHub's API. I wonder if this is throttling. I added a bit more logging, could you please try again and see if it's still triggered?

**Comment by jayvdb** [comment]
This time I made it through to the form asking for permissions, but then on submission of the form I am told

> Something went wrong during login. Please try again.

**Comment by berkerpeksag** [comment]
> Something went wrong during login. Please try again.

I'm also getting this when I try to log in at https://jazzband.co/account/login:

<img width="588" alt="Screen Shot 2019-04-06 at 7 31 45 PM" src="https://user-images.githubusercontent.com/26338/55672353-b5d39780-58a2-11e9-87b7-7c1dbd677a31.png">

<img width="635" alt="Screen Shot 2019-04-06 at 7 32 00 PM" src="https://user-images.githubusercontent.com/26338/55672357-bf5cff80-58a2-11e9-9ef8-053dd6b25935.png">

**Comment by jezdez** [comment]
Okay folks, I've done some light refactoring and moved the code base to Flask-Dance for the GitHub auth handling, simply to be able to see more what's going on and handle GitHub rate limiting better. Could you please try again?

**Comment by jayvdb** [comment]
Works perfectly for me. Nicely done.

**Comment by berkerpeksag** [comment]
Works for me as well, thank you very much! :)

**Comment by jezdez** [comment]
Nice, closing this for now. Please let me know if it returns.
