### ISSUE TITLE
Increase package upload size limit

### ISSUE THREAD

**Issue by albertyw** [jazzband/website#41]
I'm getting an error when uploading a silk package to the jazzband server: https://travis-ci.org/jazzband/silk/jobs/326440835

```
HTTPError: 413 Client Error: Request Entity Too Large for url: https://jazzband.co/projects/silk/upload
```

My local build is saying that the wheel and gzip packages are a bit less than 2MB whereas the pypi limit seems to be 60MB (https://github.com/pypa/packaging-problems/issues/86).  Can we increase the jazzband server's request size limit to 60MB to match pypi?

**Comment by jezdez** [comment]
Woops, only saw this now, a better place would have been the roadies repo, which I check more often than this repo (I get a lot of GitHub notifications).

**Comment by jezdez** [comment]
Fixed.
