### ISSUE TITLE
/about/guidelines Broken Contributing guideline example link

### ISSUE THREAD

**Issue by collinanderson** [jazzband/website#963]
Hi All,

Thanks for all of your work maintaining various Django packages.

FYI I was reading your guidelines page, I found a broken link.

https://jazzband.co/about/guidelines says:
"See this website’s contributing guideline for how it’d look like. Feel free to add a similar paragraph to your README file."

"contributing guideline" links here, but that link is broken.
https://github.com/jazzband/website/blob/master/CONTRIBUTING.md

I just wanted to let you know in case you wanted to update the link or change the text.

Thanks,
Collin

**Comment by jezdez** [comment]
Good catch, thanks @collinanderson!
